### ISSUE TITLE
Negative redundancy in `RearCodedListBuilder::print_stats()` 

### ISSUE THREAD

**Issue by progval** [vigna/sux-rs#18]
While on current master (9cafac06c95c2d916b76dc374a6f9d976bf65456):

```rust
$ cat examples/rcl_stats_crash.rs              
use sux::prelude::*;

pub fn main() {
    let mut rclb = RearCodedListBuilder::new(10000);
    rclb.push("UkVBRE1FLm1k");
    rclb.push("VE9ETy50eHQ=");
    rclb.push("b2xk");
    rclb.push("b2xkcHJvamVjdA==");
    rclb.push("cGFyc2VyLmM=");
    rclb.push("cmVmcy90YWdzL3YxLjA=");
    rclb.push("cmVmcy90YWdzL3YyLjAtYW5vbnltb3Vz");
    rclb.push("cmVmcy9oZWFkcy9tYXN0ZXI=");
    rclb.push("dGVzdHM=");

    rclb.print_stats();
}
```

```
 RUST_BACKTRACE=1 cargo run --example=rcl_stats_crash
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/rcl_stats_crash`
     max_block_bytes:          0
     avg_block_bytes:      0.000
             max_lcp:         15
             avg_lcp:      3.000
         max_str_len:         32
         avg_str_len:     15.556
          data_bytes:   130.000B                 130 
         codes_bytes:     8.000B                   8 
      suffixes_bytes:   122.000B                 122 
          ptrs_bytes:     8.000B                   8 
   uncompressed_size:   140.000B                 140 
          total_size:   306.000B                 306 
        optimal_size:   131.000B                 131 
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 6', src/dict/rear_coded_list.rs:260:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:162:5
   3: sux::dict::rear_coded_list::RearCodedListBuilder::print_stats::human
             at ./src/dict/rear_coded_list.rs:260:58
   4: sux::dict::rear_coded_list::RearCodedListBuilder::print_stats
             at ./src/dict/rear_coded_list.rs:275:9
   5: rcl_stats_crash::main
             at ./examples/rcl_stats_crash.rs:15:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

because `self.stats.redundancy` is `-1` (and interpreted as usize)

**Comment by vigna** [comment]
@zommiommy thoughts?

**Comment by zommiommy** [comment]
solved
